use utoipa::OpenApi;
use olymp_auth::handlers::*;
use olymp_auth::notifications::{NotificationPreferences, UpdateNotificationPreferences};
use olymp_auth::user::UserProfile;
use olymp_core::response::{ApiErrorBody, Meta};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Olymp Engine API",
        version = "0.1.0",
        description = "Olympiad LMS backend API built with Rust and Axum",
    ),
    paths(
        // Auth
        olymp_auth::handlers::request_magic_link,
        olymp_auth::handlers::magic_link_callback,
        olymp_auth::handlers::register,
        olymp_auth::handlers::login,
        olymp_auth::handlers::logout,
        olymp_auth::handlers::refresh,
        olymp_auth::handlers::forgot_password,
        olymp_auth::handlers::reset_password,
        olymp_auth::handlers::me,
        olymp_auth::handlers::update_me,
        olymp_auth::handlers::change_password,
        olymp_auth::handlers::get_notifications,
        olymp_auth::handlers::update_notifications,
        olymp_auth::handlers::my_roles,
        // Regions
        olymp_region::handlers::list_provinces,
        olymp_region::handlers::get_province,
        olymp_region::handlers::create_province,
        olymp_region::handlers::list_districts,
        olymp_region::handlers::create_district,
        // RBAC
        olymp_rbac::handlers::list_roles,
        olymp_rbac::handlers::create_role,
        olymp_rbac::handlers::update_role,
        olymp_rbac::handlers::list_permissions,
        olymp_rbac::handlers::get_role_permissions,
        olymp_rbac::handlers::assign_role_permissions,
        olymp_rbac::handlers::list_assignments,
        olymp_rbac::handlers::create_assignment,
        olymp_rbac::handlers::update_assignment,
        olymp_rbac::handlers::delete_assignment,
        // Participants
        olymp_participant::handlers::list_event_participants,
        olymp_participant::handlers::register_participant,
        olymp_participant::handlers::get_participant,
        olymp_participant::handlers::update_participant,
        olymp_participant::handlers::verify_participant,
        olymp_participant::handlers::approve_participant,
        olymp_participant::handlers::reject_participant,
        olymp_participant::handlers::list_stage_participants,
        olymp_participant::handlers::my_participations,
        olymp_participant::handlers::batch_verify,
        olymp_participant::handlers::batch_approve,
        olymp_participant::handlers::batch_reject,
        // Certificates
        olymp_certificate::handlers::create_template,
        olymp_certificate::handlers::list_templates,
        olymp_certificate::handlers::get_template,
        olymp_certificate::handlers::update_template,
        olymp_certificate::handlers::generate_certificates,
        olymp_certificate::handlers::list_participant_certificates,
        olymp_certificate::handlers::get_certificate,
        olymp_certificate::handlers::finalize_event,
        // Ranking
        olymp_ranking::handlers::get_ranking_rule,
        olymp_ranking::handlers::upsert_ranking_rule,
        olymp_ranking::handlers::calculate_ranking,
        olymp_ranking::handlers::get_ranking,
        olymp_ranking::handlers::review_ranking,
        olymp_ranking::handlers::approve_ranking,
        olymp_ranking::handlers::publish_ranking,
        olymp_ranking::handlers::promote,
        // Monitoring
        olymp_monitoring::handlers::create_cheating_log,
        olymp_monitoring::handlers::list_cheating_logs,
        olymp_monitoring::handlers::update_progress,
        olymp_monitoring::handlers::get_progress,
        olymp_monitoring::handlers::list_exam_progress,
        olymp_monitoring::handlers::query_audit_logs,
        olymp_monitoring::handlers::monitor_stream,
        // Exams
        olymp_exam::handlers::my_sessions,
        olymp_exam::handlers::list_exams,
        olymp_exam::handlers::create_exam,
        olymp_exam::handlers::get_exam,
        olymp_exam::handlers::update_exam,
        olymp_exam::handlers::list_questions,
        olymp_exam::handlers::create_question,
        olymp_exam::handlers::update_question,
        olymp_exam::handlers::delete_question,
        olymp_exam::handlers::assign_session,
        olymp_exam::handlers::get_session,
        olymp_exam::handlers::start_session,
        olymp_exam::handlers::save_answer,
        olymp_exam::handlers::list_answers,
        olymp_exam::handlers::submit_session,
        // Events
        olymp_event::handlers::list_education_levels,
        olymp_event::handlers::create_education_level,
        olymp_event::handlers::list_subjects,
        olymp_event::handlers::create_subject,
        olymp_event::handlers::list_events,
        olymp_event::handlers::get_event,
        olymp_event::handlers::create_event,
        olymp_event::handlers::update_event,
        olymp_event::handlers::list_stages,
        olymp_event::handlers::create_stage,
        olymp_event::handlers::update_stage,
        olymp_event::handlers::update_stage_status,
        olymp_event::handlers::list_event_categories,
        olymp_event::handlers::create_event_category,
    ),
    components(
        schemas(
            // Auth
            MagicLinkRequest,
            MagicLinkResponse,
            CallbackRequest,
            AuthResponse,
            RefreshRequest,
            RegisterRequest,
            LoginRequest,
            LogoutRequest,
            ChangePasswordRequest,
            ForgotPasswordRequest,
            ResetPasswordRequest,
            UpdateProfileRequest,
            MyRolesResponse,
            UpdateNotificationPreferences,
            NotificationPreferences,
            UserProfile,
            // Region
            olymp_region::models::Province,
            olymp_region::models::District,
            olymp_region::models::CreateProvinceRequest,
            olymp_region::models::CreateDistrictRequest,
            // Event
            olymp_event::models::EducationLevel,
            olymp_event::models::Subject,
            olymp_event::models::Event,
            olymp_event::models::Stage,
            olymp_event::models::EventCategory,
            olymp_event::models::CreateEducationLevelRequest,
            olymp_event::models::CreateSubjectRequest,
            olymp_event::models::CreateEventRequest,
            olymp_event::models::UpdateEventRequest,
            olymp_event::models::CreateStageRequest,
            olymp_event::models::UpdateStageRequest,
            olymp_event::models::UpdateStageStatusRequest,
            olymp_event::models::CreateEventCategoryRequest,
            // Core enums
            olymp_core::types::Tier,
            olymp_core::types::EventStatus,
            olymp_core::types::StageStatus,
            // RBAC
            olymp_rbac::models::Role,
            olymp_rbac::models::Permission,
            olymp_rbac::models::UserRoleAssignment,
            olymp_rbac::models::CreateRoleRequest,
            olymp_rbac::models::UpdateRoleRequest,
            olymp_rbac::models::AssignPermissionsRequest,
            olymp_rbac::models::CreateAssignmentRequest,
            olymp_rbac::models::UpdateAssignmentRequest,
            // Participants
            olymp_participant::models::Participant,
            olymp_participant::models::ParticipantStage,
            olymp_participant::models::ParticipantDetail,
            olymp_participant::models::ParticipantListItem,
            olymp_participant::models::RegisterParticipantRequest,
            olymp_participant::models::UpdateParticipantRequest,
            olymp_participant::models::VerifyRejectRequest,
            olymp_participant::models::BatchParticipantRequest,
            olymp_participant::models::BatchResult,
            // Exams
            olymp_exam::models::Exam,
            olymp_exam::models::Question,
            olymp_exam::models::QuestionForParticipant,
            olymp_exam::models::ExamSession,
            olymp_exam::models::Answer,
            olymp_exam::models::AnswerForParticipant,
            olymp_exam::models::CreateExamRequest,
            olymp_exam::models::UpdateExamRequest,
            olymp_exam::models::CreateQuestionRequest,
            olymp_exam::models::UpdateQuestionRequest,
            olymp_exam::models::AssignSessionRequest,
            olymp_exam::models::SubmitAnswerRequest,
            olymp_exam::models::BatchSubmitAnswersRequest,
            olymp_exam::models::SessionStartResponse,
            olymp_exam::models::ScoreResult,
            // Monitoring
            olymp_monitoring::models::CheatingLog,
            olymp_monitoring::models::ExamProgress,
            olymp_monitoring::models::AuditLog,
            olymp_monitoring::models::CreateCheatingLogRequest,
            olymp_monitoring::models::UpdateProgressRequest,
            olymp_monitoring::models::CreateAuditLogRequest,
            olymp_monitoring::models::AuditLogQuery,
            olymp_monitoring::models::MonitorEvent,
            // Ranking
            olymp_ranking::models::RankingRule,
            olymp_ranking::models::RankingResult,
            olymp_ranking::models::RankingEntry,
            olymp_ranking::models::RankingResultWithEntries,
            olymp_ranking::models::CreateRankingRuleRequest,
            olymp_ranking::models::UpdateRankingRuleRequest,
            olymp_ranking::models::ReviewRequest,
            olymp_ranking::models::ApproveRequest,
            olymp_ranking::models::PromotionResult,
            // Certificates
            olymp_certificate::models::CertificateTemplate,
            olymp_certificate::models::Certificate,
            olymp_certificate::models::CreateTemplateRequest,
            olymp_certificate::models::UpdateTemplateRequest,
            olymp_certificate::models::GenerateCertificatesRequest,
            olymp_certificate::models::GenerationResult,
            // Standard response envelope
            ApiErrorBody,
            Meta,
        )
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "events", description = "Olympiad event management"),
        (name = "regions", description = "Region management"),
        (name = "participants", description = "Participant management"),
        (name = "exams", description = "Exam management"),
        (name = "ranking", description = "Ranking and qualification"),
        (name = "monitoring", description = "Exam monitoring"),
        (name = "rbac", description = "Role-based access control"),
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer",
                utoipa::openapi::security::SecurityScheme::Http(
                    utoipa::openapi::security::Http::new(
                        utoipa::openapi::security::HttpAuthScheme::Bearer,
                    ),
                ),
            );
        }
    }
}
